controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_products:
    path: /api/products
    controller: App\Controller\ProductController::index
    methods: GET

api_recipes:
    path: /api/recipes
    controller: App\Controller\RecipeController::index
    methods: GET

api_blog:
    path: /api/blogs
    controller: App\Controller\BlogController::index
    methods: GET

app_register:
    path: /register
    controller: App\Controller\RegisterController::register
    methods: POST

login:
    path: /api/login_check
    controller: App\Controller\LoginController::login
